ALTER TABLE "Commerce"."Receipts"
    ADD COLUMN IF NOT EXISTS "ReceiptOrderId" VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS "PaymentId"      VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS "Status"         VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS "Type"           VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS "UserId"         BIGINT      NOT NULL;