CREATE TABLE IF NOT EXISTS "Rules"."FareRules"
(
    "RuleId" SERIAL,
    "Name" VARCHAR(150) NOT NULL,
    "Label" VARCHAR(200) NOT NULL,
    "Position" INT NOT NULL DEFAULT 0,
    "Price" DECIMAL(12,2) NOT NULL,
    "Currency" VARCHAR(5) NOT NULL DEFAULT 'RUB',
    "IsPopular" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_FareRules_RuleId" PRIMARY KEY ("RuleId")
);